In [1]:
import pandas as pd
import numpy as np

K15T = pd.read_csv('../sql/K15T_UNEMPLOYED_RESIDENTS_BY_PREVIOUS_OCCUPATION_AND_SEX.csv')
K16 = pd.read_csv('../sql/K16_UNEMPLOYED_RESIDENT_PMETs_AND_NON-PMETs__BY_AGE.csv')
K17 = pd.read_csv('../sql/K17_LONG-TERM_UNEMPLOYED_RESIDENT_BY_PMET_STATUS_AND_AGE.csv')

In [2]:
K15T

,Occupation,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Gender,Group,Status
0,Managers & Administrators (Including Working P...,6.1,5.6,7.4,6.7,6.0,5.5,5.3,7.2,6.4,3.5,7.4,Male,Residents Aged Fifteen Years And Over,Unemployed
1,Professionals,4.9,5.2,6.7,6.1,7.6,5.8,10.3,10.7,9.4,9.6,7.9,Male,Residents Aged Fifteen Years And Over,Unemployed
2,Associate Professionals & Technicians,6.3,7.5,7.2,7.7,7.2,8.7,11.3,9.8,6.2,7.2,8.8,Male,Residents Aged Fifteen Years And Over,Unemployed
3,Clerical Support Workers,4.3,4.5,4.5,4.7,3.7,4.8,5.0,4.6,3.5,3.0,3.1,Male,Residents Aged Fifteen Years And Over,Unemployed
4,Service & Sales Workers,6.5,7.4,5.9,7.8,5.8,7.4,8.2,7.0,5.4,4.2,4.5,Male,Residents Aged Fifteen Years And Over,Unemployed
5,Craftsmen & Related Trades Workers,2.0,2.4,2.3,2.2,2.3,2.1,2.9,1.4,1.1,1.5,1.1,Male,Residents Aged Fifteen Years And Over,Unemployed
6,Plant & Machine Operators & Assemblers,4.2,3.8,4.2,4.7,4.6,3.6,5.6,4.9,4.0,2.7,3.1,Male,Residents Aged Fifteen Years And Over,Unemployed
7,"Cleaners, Labourers & Related Workers",4.1,3.8,3.0,3.8,3.2,3.9,6.0,3.3,4.1,3.8,3.1,Male,Residents Aged Fifteen Years And Over,Unemployed
8,Others,0.2,0.2,0.1,0.3,0.4,0.6,0.2,0.5,0.2,0.1,0.3,Male,Residents Aged Fifteen Years And Over,Unemployed
9,Managers & Administrators (Including Working P...,3.3,2.5,3.1,3.4,3.5,3.3,3.3,5.6,3.6,2.8,3.6,Female,Residents Aged Fifteen Years And Over,Unemployed
10,Professionals,5.6,5.5,6.4,6.9,6.5,7.1,7.5,10.1,7.7,6.8,6.7,Female,Residents Aged Fifteen Years And Over,Unemployed
11,Associate Professionals & Technicians,6.4,6.1,8.1,7.2,7.1,8.7,10.5,7.3,6.3,6.4,6.9,Female,Residents Aged Fifteen Years And Over,Unemployed
12,Clerical Support Workers,9.5,10.2,10.8,10.4,8.8,11.1,12.9,11.1,9.9,8.6,8.4,Female,Residents Aged Fifteen Years And Over,Unemployed
13,Service & Sales Workers,6.5,7.5,7.5,7.3,6.7,8.8,13.4,8.9,7.6,5.5,4.5,Female,Residents Aged Fifteen Years And Over,Unemployed
14,Craftsmen & Related Trades Workers,0.2,0.3,0.5,0.2,0.3,0.5,0.6,0.2,0.1,0.4,0.3,Female,Residents Aged Fifteen Years And Over,Unemployed
15,Plant & Machine Operators & Assemblers,1.2,0.8,0.5,0.8,0.4,0.6,0.5,0.5,0.6,0.3,0.5,Female,Residents Aged Fifteen Years And Over,Unemployed
16,"Cleaners, Labourers & Related Workers",3.4,2.6,3.6,2.7,3.1,2.4,5.1,3.5,2.9,2.5,1.5,Female,Residents Aged Fifteen Years And Over,Unemployed
17,Others,NaN,NaN,NaN,NaN,0.1,0.1,0.1,0.1,NaN,NaN,0.1,Female,Residents Aged Fifteen Years And Over,Unemployed
18,others who have never worked before,7.0,8.6,10.5,11.5,11.7,13.0,14.2,14.5,8.5,14.9,9.2,ALL,Residents Aged Fifteen Years And Over,Unemployed

In [3]:
K16

,Age,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Pmet_Status,Group,Status
0,15 - 29,8.3,7.3,8.2,7.4,8.6,8.8,8.9,9.0,8.6,6.0,7.9,PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
1,30 - 39,8.6,7.1,10.3,9.0,8.7,8.1,11.2,12.3,8.9,8.0,9.3,PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
2,40 - 49,8.7,8.9,9.9,10.8,9.9,11.2,12.6,16.5,8.8,11.2,9.9,PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
3,50 & Over,6.9,8.9,10.4,10.7,10.8,11.0,15.5,12.9,13.3,11.2,14.1,PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
4,15 - 29,15.2,16.0,13.7,15.3,12.9,15.5,19.5,12.0,7.9,8.3,7.5,Non-PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
5,30 - 39,6.4,5.4,5.9,5.4,4.9,5.9,7.9,7.2,8.1,5.2,5.3,Non-PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
6,40 - 49,6.8,6.2,6.9,6.4,6.2,6.5,8.6,8.8,7.5,5.7,4.2,Non-PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
7,50 & Over,13.8,15.8,16.4,17.8,15.4,18.0,24.5,18.1,15.7,13.4,13.3,Non-PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
8,ALL,7.0,8.9,10.6,11.6,11.6,13.0,14.2,14.4,8.7,14.8,9.5,ALL,others who have never worked before,Unemployed

In [4]:
occup_list = K15T['Occupation'].unique()[:3]
occup_list

array(['Managers & Administrators (Including Working Proprietors)',
       'Professionals', 'Associate Professionals & Technicians'],
      dtype=object)

In [5]:
# check for the occupations are PMETs
K15T[['2024']][K15T['Occupation'].isin(occup_list)].sum()

2024    41.3
dtype: float64

In [6]:
K16[['2024']][K16['Pmet_Status'] == 'PMETs'].sum()

2024    41.2
dtype: float64

In [7]:
if 'Pmet_Status' not in K15T.columns:
    K15T['Pmet_Status'] = K15T['Occupation'].apply(lambda x: 'PMETs' if x in occup_list else 'Non-PMETs')
K15T

,Occupation,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Gender,Group,Status,Pmet_Status
0,Managers & Administrators (Including Working P...,6.1,5.6,7.4,6.7,6.0,5.5,5.3,7.2,6.4,3.5,7.4,Male,Residents Aged Fifteen Years And Over,Unemployed,PMETs
1,Professionals,4.9,5.2,6.7,6.1,7.6,5.8,10.3,10.7,9.4,9.6,7.9,Male,Residents Aged Fifteen Years And Over,Unemployed,PMETs
2,Associate Professionals & Technicians,6.3,7.5,7.2,7.7,7.2,8.7,11.3,9.8,6.2,7.2,8.8,Male,Residents Aged Fifteen Years And Over,Unemployed,PMETs
3,Clerical Support Workers,4.3,4.5,4.5,4.7,3.7,4.8,5.0,4.6,3.5,3.0,3.1,Male,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
4,Service & Sales Workers,6.5,7.4,5.9,7.8,5.8,7.4,8.2,7.0,5.4,4.2,4.5,Male,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
5,Craftsmen & Related Trades Workers,2.0,2.4,2.3,2.2,2.3,2.1,2.9,1.4,1.1,1.5,1.1,Male,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
6,Plant & Machine Operators & Assemblers,4.2,3.8,4.2,4.7,4.6,3.6,5.6,4.9,4.0,2.7,3.1,Male,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
7,"Cleaners, Labourers & Related Workers",4.1,3.8,3.0,3.8,3.2,3.9,6.0,3.3,4.1,3.8,3.1,Male,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
8,Others,0.2,0.2,0.1,0.3,0.4,0.6,0.2,0.5,0.2,0.1,0.3,Male,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
9,Managers & Administrators (Including Working P...,3.3,2.5,3.1,3.4,3.5,3.3,3.3,5.6,3.6,2.8,3.6,Female,Residents Aged Fifteen Years And Over,Unemployed,PMETs
10,Professionals,5.6,5.5,6.4,6.9,6.5,7.1,7.5,10.1,7.7,6.8,6.7,Female,Residents Aged Fifteen Years And Over,Unemployed,PMETs
11,Associate Professionals & Technicians,6.4,6.1,8.1,7.2,7.1,8.7,10.5,7.3,6.3,6.4,6.9,Female,Residents Aged Fifteen Years And Over,Unemployed,PMETs
12,Clerical Support Workers,9.5,10.2,10.8,10.4,8.8,11.1,12.9,11.1,9.9,8.6,8.4,Female,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
13,Service & Sales Workers,6.5,7.5,7.5,7.3,6.7,8.8,13.4,8.9,7.6,5.5,4.5,Female,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
14,Craftsmen & Related Trades Workers,0.2,0.3,0.5,0.2,0.3,0.5,0.6,0.2,0.1,0.4,0.3,Female,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
15,Plant & Machine Operators & Assemblers,1.2,0.8,0.5,0.8,0.4,0.6,0.5,0.5,0.6,0.3,0.5,Female,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
16,"Cleaners, Labourers & Related Workers",3.4,2.6,3.6,2.7,3.1,2.4,5.1,3.5,2.9,2.5,1.5,Female,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
17,Others,NaN,NaN,NaN,NaN,0.1,0.1,0.1,0.1,NaN,NaN,0.1,Female,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
18,others who have never worked before,7.0,8.6,10.5,11.5,11.7,13.0,14.2,14.5,8.5,14.9,9.2,ALL,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs

In [8]:
K15T_group_Pmet = K15T[K15T['Occupation'] != 'others who have never worked before'].groupby(['Pmet_Status', 'Group','Status','Gender'], as_index=False).sum().drop('Occupation', axis =1)
print(K15T_group_Pmet['2016'][K15T_group_Pmet['Pmet_Status'] == 'PMETs'].sum())
K15T_group_Pmet

38.900000000000006

,Pmet_Status,Group,Status,Gender,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Non-PMETs,Residents Aged Fifteen Years And Over,Unemployed,Female,20.8,21.4,22.9,21.4,19.4,23.5,32.6,24.3,21.1,17.3,15.3
1,Non-PMETs,Residents Aged Fifteen Years And Over,Unemployed,Male,21.3,22.1,20.0,23.5,20.0,22.4,27.9,21.7,18.3,15.3,15.2
2,PMETs,Residents Aged Fifteen Years And Over,Unemployed,Female,15.3,14.1,17.6,17.5,17.1,19.1,21.3,23.0,17.6,16.0,17.2
3,PMETs,Residents Aged Fifteen Years And Over,Unemployed,Male,17.3,18.3,21.3,20.5,20.8,20.0,26.9,27.7,22.0,20.3,24.1

In [9]:
K16_drop = K16[K16['Group'] != 'others who have never worked before']
print(K16_drop['2016'][K16_drop['Pmet_Status'] == 'PMETs'].sum())
K16_drop.head()

38.8

,Age,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Pmet_Status,Group,Status
0,15 - 29,8.3,7.3,8.2,7.4,8.6,8.8,8.9,9.0,8.6,6.0,7.9,PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
1,30 - 39,8.6,7.1,10.3,9.0,8.7,8.1,11.2,12.3,8.9,8.0,9.3,PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
2,40 - 49,8.7,8.9,9.9,10.8,9.9,11.2,12.6,16.5,8.8,11.2,9.9,PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
3,50 & Over,6.9,8.9,10.4,10.7,10.8,11.0,15.5,12.9,13.3,11.2,14.1,PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed
4,15 - 29,15.2,16.0,13.7,15.3,12.9,15.5,19.5,12.0,7.9,8.3,7.5,Non-PMETs,Residents Aged Fifteen Years And Over Who Have...,Unemployed

In [10]:
'''import numpy as np
import pandas as pd
from scipy.optimize import minimize

# Example Data (Replace with actual data from your dataframe)
k2 = np.array([13.8, 7.2, 8.0, 7.0, 4.5, 1.0])  # k2 data from 2014
k3 = np.array([8.3, 7.6, 5.6, 7.3, 12.7])  # k3 data from 2014

# Objective function
def objective(w, array1, array2):
    # Reshape w into a 6x5 matrix
    W = w.reshape(len(array1), len(array2))
    
    # Calculate the predicted k2 values from the linear combination
    array1_calc = np.dot(W, array2)
    
    # Objective is the squared error between calculated and target k2 values
    return np.sum((array1_calc - array1)**2)

def optimization (array1, array1_labels, array2 ,array2_labels):
    array1 = np.asarray(array1)
    array2 = np.asarray(array2)
    # array1_labels = np.asarray(array1_labels)
    # array2_labels = np.asarray(array2_labels)

    # Constraints on weights: each column of the reshaped weights must sum to 1
    constraints = []
    for j in range(len(array2)):
        def constraint_func_factory(idx):
            return lambda w, idx=idx: np.sum(w.reshape(len(array1), len(array2))[:, idx]) - 1
        constraints.append({'type': 'eq', 'fun': constraint_func_factory(j)})
    
    # Initial guess for the weights
    w0 = np.full(len(array1) * len(array2), 1.0 / len(array1))
    
    # Bounds for weights (between 0 and 1)
    bounds = [(0, 1)] * (len(array1) * len(array2))
    
    # Optimization
    result = minimize(objective, w0, args=(array1, array2), method='SLSQP', constraints=constraints, bounds=bounds)
    
    # Create a DataFrame to show the results in a table format
    weights_matrix = result.x.reshape(len(array1), len(array2))
    weights_df = pd.DataFrame(weights_matrix,
                              columns = [name for j,name in enumerate(array2_labels.tolist())],
                              #columns=[f'k16_{j+1}' for j in range(len(array2))],
                              #index=[f'k15T_{i+1}' for i in range(len(array1))])
                              index=[name for i,name in enumerate(array1_labels.tolist())])

    # Add diagnostics
    weights_df['Original k15T'] = array1
    weights_df['Calculated k15T'] = np.dot(weights_matrix, array2)
    weights_df['Error'] = weights_df['Calculated k15T'] - weights_df['Original k15T']
    
    return weights_df

weights_df = optimization (K15T_group_Pmet['2015'][K15T_group_Pmet['Pmet_Status'] == 'PMETs'],
                           K15T_group_Pmet['Gender'][K15T_group_Pmet['Pmet_Status'] == 'PMETs'],
                           K16_drop['2015'][K16_drop['Pmet_Status'] == 'PMETs'],
                           K16_drop['Age'][K16_drop['Pmet_Status'] == 'PMETs']
                          )

# Display the table
print("Detailed Results Table:")
print("-----------------------")
print(weights_df)

# Step 1: Identify columns to melt (age groups)
age_group_cols =  K16_drop['Age'][K16_drop['Pmet_Status'] == 'PMETs']

# Step 2: Melt while keeping the gender (currently in index)
melted = weights_df.reset_index().melt(
    id_vars='index',               # 'index' becomes the gender column
    value_vars=age_group_cols,     # melt age group weights
    var_name='Age_Group',
    value_name='Weight'
)

# Step 3: Rename the index column
melted = melted.rename(columns={'index': 'Gender'})
print(melted)


# Step 1: Initialize the new column
melted['Count'] = 0.0

# Step 2: Filter K16_drop once to avoid repeating
k16_filtered = K16_drop[K16_drop['Pmet_Status'] == 'PMETs'].reset_index(drop=True)

# Step 3: Loop and match
for i in range(len(melted)):
    for k in range(len(k16_filtered)):
        if melted['Age_Group'].iloc[i] == k16_filtered['Age'].iloc[k]:
            melted.at[i, 'Count'] = melted['Weight'].iloc[i] * k16_filtered['2015'].iloc[k]
melted
'''

'import numpy as np\nimport pandas as pd\nfrom scipy.optimize import minimize\n\n# Example Data (Replace with actual data from your dataframe)\nk2 = np.array([13.8, 7.2, 8.0, 7.0, 4.5, 1.0])  # k2 data from 2014\nk3 = np.array([8.3, 7.6, 5.6, 7.3, 12.7])  # k3 data from 2014\n\n# Objective function\ndef objective(w, array1, array2):\n    # Reshape w into a 6x5 matrix\n    W = w.reshape(len(array1), len(array2))\n    \n    # Calculate the predicted k2 values from the linear combination\n    array1_calc = np.dot(W, array2)\n    \n    # Objective is the squared error between calculated and target k2 values\n    return np.sum((array1_calc - array1)**2)\n\ndef optimization (array1, array1_labels, array2 ,array2_labels):\n    array1 = np.asarray(array1)\n    array2 = np.asarray(array2)\n    # array1_labels = np.asarray(array1_labels)\n    # array2_labels = np.asarray(array2_labels)\n\n    # Constraints on weights: each column of the reshaped weights must sum to 1\n    constraints = []\n    for j in range(len(array2)):\n        def constraint_func_factory(idx):\n            return lambda w, idx=idx: np.sum(w.reshape(len(array1), len(array2))[:, idx]) - 1\n        constraints.append({\'type\': \'eq\', \'fun\': constraint_func_factory(j)})\n    \n    # Initial guess for the weights\n    w0 = np.full(len(array1) * len(array2), 1.0 / len(array1))\n    \n    # Bounds for weights (between 0 and 1)\n    bounds = [(0, 1)] * (len(array1) * len(array2))\n    \n    # Optimization\n    result = minimize(objective, w0, args=(array1, array2), method=\'SLSQP\', constraints=constraints, bounds=bounds)\n    \n    # Create a DataFrame to show the results in a table format\n    weights_matrix = result.x.reshape(len(array1), len(array2))\n    weights_df = pd.DataFrame(weights_matrix,\n                              columns = [name for j,name in enumerate(array2_labels.tolist())],\n                              #columns=[f\'k16_{j+1}\' for j in range(len(array2))],\n                              #index=[f\'k15T_{i+1}\' for i in range(len(array1))])\n                              index=[name for i,name in enumerate(array1_labels.tolist())])\n\n    # Add diagnostics\n    weights_df[\'Original k15T\'] = array1\n    weights_df[\'Calculated k15T\'] = np.dot(weights_matrix, array2)\n    weights_df[\'Error\'] = weights_df[\'Calculated k15T\'] - weights_df[\'Original k15T\']\n    \n    return weights_df\n\nweights_df = optimization (K15T_group_Pmet[\'2015\'][K15T_group_Pmet[\'Pmet_Status\'] == \'PMETs\'],\n                           K15T_group_Pmet[\'Gender\'][K15T_group_Pmet[\'Pmet_Status\'] == \'PMETs\'],\n                           K16_drop[\'2015\'][K16_drop[\'Pmet_Status\'] == \'PMETs\'],\n                           K16_drop[\'Age\'][K16_drop[\'Pmet_Status\'] == \'PMETs\']\n                          )\n\n# Display the table\nprint("Detailed Results Table:")\nprint("-----------------------")\nprint(weights_df)\n\n# Step 1: Identify columns to melt (age groups)\nage_group_cols =  K16_drop[\'Age\'][K16_drop[\'Pmet_Status\'] == \'PMETs\']\n\n# Step 2: Melt while keeping the gender (currently in index)\nmelted = weights_df.reset_index().melt(\n    id_vars=\'index\',               # \'index\' becomes the gender column\n    value_vars=age_group_cols,     # melt age group weights\n    var_name=\'Age_Group\',\n    value_name=\'Weight\'\n)\n\n# Step 3: Rename the index column\nmelted = melted.rename(columns={\'index\': \'Gender\'})\nprint(melted)\n\n\n# Step 1: Initialize the new column\nmelted[\'Count\'] = 0.0\n\n# Step 2: Filter K16_drop once to avoid repeating\nk16_filtered = K16_drop[K16_drop[\'Pmet_Status\'] == \'PMETs\'].reset_index(drop=True)\n\n# Step 3: Loop and match\nfor i in range(len(melted)):\n    for k in range(len(k16_filtered)):\n        if melted[\'Age_Group\'].iloc[i] == k16_filtered[\'Age\'].iloc[k]:\n            melted.at[i, \'Count\'] = melted[\'Weight\'].iloc[i] * k16_filtered[\'2015\'].iloc[k]\nmelted\n'

In [11]:
import numpy as np
import pandas as pd
from scipy.optimize import minimize

# ------------------------------
# Optimization function
# ------------------------------
def objective(w, array1, array2):
    W = w.reshape(len(array1), len(array2))
    return np.sum((np.dot(W, array2) - array1) ** 2)

def optimize_weights(array1, array1_labels, array2, array2_labels):
    array1 = np.asarray(array1)
    array2 = np.asarray(array2)

    # Constraint: each column (age group) sums to 1
    constraints = [
        {'type': 'eq', 'fun': lambda w, idx=idx: np.sum(w.reshape(len(array1), len(array2))[:, idx]) - 1}
        for idx in range(len(array2))
    ]
    
    w0 = np.full(len(array1) * len(array2), 1.0 / len(array1))
    bounds = [(0, 1)] * len(w0)

    result = minimize(objective, w0, args=(array1, array2), method='SLSQP', constraints=constraints, bounds=bounds)
    weights_matrix = result.x.reshape(len(array1), len(array2))

    weights_df = pd.DataFrame(
        weights_matrix,
        index=array1_labels.tolist(),
        columns=array2_labels.tolist()
    )

    weights_df['Original k15T'] = array1
    weights_df['Calculated k15T'] = weights_df[array2_labels.tolist()].dot(array2)
    weights_df['Error'] = weights_df['Calculated k15T'] - weights_df['Original k15T']
    
    return weights_df

def process_split (year, Pmet_Status):                                                                                                                    # ------------------------------
    # Apply optimization
    # ------------------------------
    k15_vals = K15T_group_Pmet[year][K15T_group_Pmet['Pmet_Status'] == Pmet_Status]
    k15_labels = K15T_group_Pmet['Gender'][K15T_group_Pmet['Pmet_Status'] == Pmet_Status]
    k16_vals = K16_drop[year][K16_drop['Pmet_Status'] == Pmet_Status]
    k16_labels = K16_drop['Age'][K16_drop['Pmet_Status'] == Pmet_Status]
    
    weights_df = optimize_weights(k15_vals, k15_labels, k16_vals, k16_labels)
    
    #print("Detailed Results Table:")
    #print("-----------------------")
    #print(weights_df)
    
    # ------------------------------
    # Melt weights table to long format
    # ------------------------------
    melted = weights_df.reset_index(names='Gender').melt(
        id_vars='Gender',
        value_vars=k16_labels.tolist(),
        var_name='Age_Group',
        value_name='Weight'
    )
    #print(melted)
    
    # ------------------------------
    # Merge to apply weights (no loop needed)
    # ------------------------------
    k16_values = K16_drop[['Age', year]][K16_drop['Pmet_Status'] == Pmet_Status].drop_duplicates()
    melted = melted.merge(k16_values, left_on='Age_Group', right_on='Age', how='left')
    melted['Count'] = melted['Weight'] * melted[year]
    melted = melted.drop(columns=['Age', year])
    melted = melted.reset_index(drop=True)
    
    # Final result
    melted['Year'] = year
    return melted

# Initialize empty list to store results
all_results = []

# Get unique Pmet_Status values from the combined dataset (you can use either K15T_group_Pmet or K16_drop)
pmet_status_list = K15T_group_Pmet['Pmet_Status'].unique()

# Loop through each year and Pmet_Status
for year in range(2014, 2025):
    year_str = str(year)
    for pmet_status in pmet_status_list:
        try:
            melted = process_split(year_str, pmet_status)
            melted['Pmet_Status'] = pmet_status  # Add status as a column
            all_results.append(melted)
        except KeyError:
            print(f"Year {year} or status '{pmet_status}' not found in data — skipping.")
        except Exception as e:
            print(f"Error processing year {year} and status '{pmet_status}': {e}")

# Combine all results into one DataFrame
final_result = pd.concat(all_results, ignore_index=True)

# View result
print(final_result)

     Gender  Age_Group    Weight     Count  Year Pmet_Status
0    Female    15 - 29  0.494076  7.509953  2014   Non-PMETs
1      Male    15 - 29  0.505924  7.690047  2014   Non-PMETs
2    Female    30 - 39  0.494076  3.162085  2014   Non-PMETs
3      Male    30 - 39  0.505924  3.237915  2014   Non-PMETs
4    Female    40 - 49  0.494076  3.359716  2014   Non-PMETs
..      ...        ...       ...       ...   ...         ...
171    Male    30 - 39  0.583738  5.428762  2024       PMETs
172  Female    40 - 49  0.416262  4.120995  2024       PMETs
173    Male    40 - 49  0.583738  5.779005  2024       PMETs
174  Female  50 & Over  0.416262  5.869296  2024       PMETs
175    Male  50 & Over  0.583738  8.230704  2024       PMETs

[176 rows x 6 columns]

In [12]:
final_result

     Gender  Age_Group    Weight     Count  Year Pmet_Status
0    Female    15 - 29  0.494076  7.509953  2014   Non-PMETs
1      Male    15 - 29  0.505924  7.690047  2014   Non-PMETs
2    Female    30 - 39  0.494076  3.162085  2014   Non-PMETs
3      Male    30 - 39  0.505924  3.237915  2014   Non-PMETs
4    Female    40 - 49  0.494076  3.359716  2014   Non-PMETs
..      ...        ...       ...       ...   ...         ...
171    Male    30 - 39  0.583738  5.428762  2024       PMETs
172  Female    40 - 49  0.416262  4.120995  2024       PMETs
173    Male    40 - 49  0.583738  5.779005  2024       PMETs
174  Female  50 & Over  0.416262  5.869296  2024       PMETs
175    Male  50 & Over  0.583738  8.230704  2024       PMETs

[176 rows x 6 columns]

In [13]:
K15T.head()

,Occupation,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Gender,Group,Status,Pmet_Status
0,Managers & Administrators (Including Working P...,6.1,5.6,7.4,6.7,6.0,5.5,5.3,7.2,6.4,3.5,7.4,Male,Residents Aged Fifteen Years And Over,Unemployed,PMETs
1,Professionals,4.9,5.2,6.7,6.1,7.6,5.8,10.3,10.7,9.4,9.6,7.9,Male,Residents Aged Fifteen Years And Over,Unemployed,PMETs
2,Associate Professionals & Technicians,6.3,7.5,7.2,7.7,7.2,8.7,11.3,9.8,6.2,7.2,8.8,Male,Residents Aged Fifteen Years And Over,Unemployed,PMETs
3,Clerical Support Workers,4.3,4.5,4.5,4.7,3.7,4.8,5.0,4.6,3.5,3.0,3.1,Male,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs
4,Service & Sales Workers,6.5,7.4,5.9,7.8,5.8,7.4,8.2,7.0,5.4,4.2,4.5,Male,Residents Aged Fifteen Years And Over,Unemployed,Non-PMETs

In [14]:
K15T[(K15T['Pmet_Status'] == 'PMETs') & (K15T['Gender']== 'Male')]#['2016'].sum()

,Occupation,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Gender,Group,Status,Pmet_Status
0,Managers & Administrators (Including Working P...,6.1,5.6,7.4,6.7,6.0,5.5,5.3,7.2,6.4,3.5,7.4,Male,Residents Aged Fifteen Years And Over,Unemployed,PMETs
1,Professionals,4.9,5.2,6.7,6.1,7.6,5.8,10.3,10.7,9.4,9.6,7.9,Male,Residents Aged Fifteen Years And Over,Unemployed,PMETs
2,Associate Professionals & Technicians,6.3,7.5,7.2,7.7,7.2,8.7,11.3,9.8,6.2,7.2,8.8,Male,Residents Aged Fifteen Years And Over,Unemployed,PMETs

In [15]:
final_result[(final_result['Year'] == '2016') & (final_result['Gender']== 'Male') & (final_result['Pmet_Status'] == 'PMETs')]#['Count'].sum()

   Gender  Age_Group   Weight     Count  Year Pmet_Status
41   Male    15 - 29  0.54768  4.490980  2016       PMETs
43   Male    30 - 39  0.54768  5.641108  2016       PMETs
45   Male    40 - 49  0.54768  5.422036  2016       PMETs
47   Male  50 & Over  0.54768  5.695876  2016       PMETs

In [16]:
# ------------------------------
# Apply optimization
# ------------------------------
k15_vals = K15T[(K15T['Pmet_Status'] == 'PMETs') & (K15T['Gender']== 'Male')]['2016']
k15_labels = K15T[(K15T['Pmet_Status'] == 'PMETs') & (K15T['Gender']== 'Male')]['Occupation']
k16_vals = final_result[(final_result['Year'] == '2016') & (final_result['Gender']== 'Male') & (final_result['Pmet_Status'] == 'PMETs')]['Count']
k16_labels = final_result[(final_result['Year'] == '2016') & (final_result['Gender']== 'Male') & (final_result['Pmet_Status'] == 'PMETs')]['Age_Group']

weights_df = optimize_weights(k15_vals, k15_labels, k16_vals, k16_labels)

print("Detailed Results Table:")
print("-----------------------")
print(weights_df)

# Melt weights table to long format
melted = weights_df.reset_index(names='Occupation').melt(
    id_vars='Occupation',
    value_vars=k16_labels.tolist(),
    var_name='Age_Group',
    value_name='Weight'
)

# Merge with final_result to get the correct marginal counts
merge_keys = ['Age_Group', 'Year', 'Gender', 'Pmet_Status']

# Recreate the key columns so you can merge cleanly
melted['Year'] = '2016'
melted['Gender'] = 'Male'
melted['Pmet_Status'] = 'PMETs'

# Merge with final_result to get age group totals
melted = melted.merge(
    final_result[merge_keys + ['Count']],
    on=merge_keys,
    how='left'
)

# Compute weighted count (Occupation by Age Group)
melted['Count'] = melted['Weight'] * melted['Count']

# Optional cleanup (rename for clarity or remove duplicate column)
# e.g., rename new Count to 'Occupation_Count'
melted = melted.rename(columns={'Count': 'Occupation_Count'})

# Final structure
melted = melted[['Occupation', 'Age_Group', 'Weight', 'Occupation_Count', 'Year', 'Gender', 'Pmet_Status']]

melted

Detailed Results Table:
-----------------------
                                                     15 - 29   30 - 39  \
Managers & Administrators (Including Working Pr...  0.348355  0.347178
Professionals                                       0.314641  0.314454
Associate Professionals & Technicians               0.337004  0.338368

                                                     40 - 49  50 & Over  \
Managers & Administrators (Including Working Pr...  0.347402   0.347122
Professionals                                       0.314490   0.314445
Associate Professionals & Technicians               0.338108   0.338433

                                                    Original k15T  \
Managers & Administrators (Including Working Pr...            7.4
Professionals                                                 6.7
Associate Professionals & Technicians                         7.2

                                                    Calculated k15T     Error
Managers & Administrators (Including Working Pr...         7.383718 -0.016282
Professionals                                              6.683135 -0.016865
Associate Professionals & Technicians                      7.183147 -0.016853

,Occupation,Age_Group,Weight,Occupation_Count,Year,Gender,Pmet_Status
0,Managers & Administrators (Including Working P...,15 - 29,0.348355,1.564455,2016,Male,PMETs
1,Professionals,15 - 29,0.314641,1.413048,2016,Male,PMETs
2,Associate Professionals & Technicians,15 - 29,0.337004,1.513477,2016,Male,PMETs
3,Managers & Administrators (Including Working P...,30 - 39,0.347178,1.958470,2016,Male,PMETs
4,Professionals,30 - 39,0.314454,1.773870,2016,Male,PMETs
5,Associate Professionals & Technicians,30 - 39,0.338368,1.908768,2016,Male,PMETs
6,Managers & Administrators (Including Working P...,40 - 49,0.347402,1.883628,2016,Male,PMETs
7,Professionals,40 - 49,0.314490,1.705175,2016,Male,PMETs
8,Associate Professionals & Technicians,40 - 49,0.338108,1.833233,2016,Male,PMETs
9,Managers & Administrators (Including Working P...,50 & Over,0.347122,1.977165,2016,Male,PMETs
10,Professionals,50 & Over,0.314445,1.791041,2016,Male,PMETs
11,Associate Professionals & Technicians,50 & Over,0.338433,1.927670,2016,Male,PMETs

In [17]:
def get_occupation_split(year, gender, pmet_status):
    year_str = str(year)

    # Get K15 values and labels (Occupation totals)
    k15_vals = K15T[(K15T['Pmet_Status'] == pmet_status) & (K15T['Gender'] == gender)][year_str]
    k15_labels = K15T[(K15T['Pmet_Status'] == pmet_status) & (K15T['Gender'] == gender)]['Occupation']

    # Get K16 values and labels (Age group totals from final_result)
    k16_filtered = final_result[
        (final_result['Year'] == year_str) &
        (final_result['Gender'] == gender) &
        (final_result['Pmet_Status'] == pmet_status)
    ]
    k16_vals = k16_filtered['Count']
    k16_labels = k16_filtered['Age_Group']

    # Run optimization
    weights_df = optimize_weights(k15_vals, k15_labels, k16_vals, k16_labels)

    # Melt to long format
    melted = weights_df.reset_index(names='Occupation').melt(
        id_vars='Occupation',
        value_vars=k16_labels.tolist(),
        var_name='Age_Group',
        value_name='Weight'
    )

    # Add columns for merging
    melted['Year'] = year_str
    melted['Gender'] = gender
    melted['Pmet_Status'] = pmet_status

    # Merge with final_result to get age group marginal totals
    merge_keys = ['Age_Group', 'Year', 'Gender', 'Pmet_Status']
    melted = melted.merge(
        final_result[merge_keys + ['Count']],
        on=merge_keys,
        how='left'
    )

    # Compute weighted counts per occupation per age group
    melted['Occupation_Count'] = melted['Weight'] * melted['Count']

    # Clean up
    melted = melted[['Occupation', 'Age_Group', 'Weight', 'Occupation_Count', 'Year', 'Gender', 'Pmet_Status']]
    
    return melted

get_occupation_split(2016, 'Male', 'PMETs')

,Occupation,Age_Group,Weight,Occupation_Count,Year,Gender,Pmet_Status
0,Managers & Administrators (Including Working P...,15 - 29,0.348355,1.564455,2016,Male,PMETs
1,Professionals,15 - 29,0.314641,1.413048,2016,Male,PMETs
2,Associate Professionals & Technicians,15 - 29,0.337004,1.513477,2016,Male,PMETs
3,Managers & Administrators (Including Working P...,30 - 39,0.347178,1.958470,2016,Male,PMETs
4,Professionals,30 - 39,0.314454,1.773870,2016,Male,PMETs
5,Associate Professionals & Technicians,30 - 39,0.338368,1.908768,2016,Male,PMETs
6,Managers & Administrators (Including Working P...,40 - 49,0.347402,1.883628,2016,Male,PMETs
7,Professionals,40 - 49,0.314490,1.705175,2016,Male,PMETs
8,Associate Professionals & Technicians,40 - 49,0.338108,1.833233,2016,Male,PMETs
9,Managers & Administrators (Including Working P...,50 & Over,0.347122,1.977165,2016,Male,PMETs
10,Professionals,50 & Over,0.314445,1.791041,2016,Male,PMETs
11,Associate Professionals & Technicians,50 & Over,0.338433,1.927670,2016,Male,PMETs

In [18]:
# Initialize list to hold all results
all_occupation_splits = []

# Loop through years, statuses, and genders
for year in range(2014, 2025):
    for pmet_status in ['PMETs', 'Non-PMETs']:
        for gender in ['Male', 'Female']:
            try:
                result = get_occupation_split(year, gender, pmet_status)
                all_occupation_splits.append(result)
            except Exception as e:
                print(f"Skipping {year}, {gender}, {pmet_status} due to error: {e}")

# Combine all into a single DataFrame
occupation_split_df = pd.concat(all_occupation_splits, ignore_index=True).drop('Weight', axis =1)

# View sample
print(occupation_split_df.shape)
occupation_split_df.head()

(792, 6)

,Occupation,Age_Group,Occupation_Count,Year,Gender,Pmet_Status
0,Managers & Administrators (Including Working P...,15 - 29,1.554971,2014,Male,PMETs
1,Professionals,15 - 29,1.246446,2014,Male,PMETs
2,Associate Professionals & Technicians,15 - 29,1.603967,2014,Male,PMETs
3,Managers & Administrators (Including Working P...,30 - 39,1.615053,2014,Male,PMETs
4,Professionals,30 - 39,1.289583,2014,Male,PMETs

In [19]:
check = occupation_split_df.groupby(['Year', 'Gender', 'Pmet_Status'])['Occupation_Count'].sum().reset_index()
print(check)
check2 = K15T.groupby(['Gender', 'Pmet_Status'])['2023'].sum().reset_index()
print(check2)

    Year  Gender Pmet_Status  Occupation_Count
0   2014  Female   Non-PMETs             20.85
1   2014  Female       PMETs             15.25
2   2014    Male   Non-PMETs             21.35
3   2014    Male       PMETs             17.25
4   2015  Female   Non-PMETs             21.35
5   2015  Female       PMETs             14.00
6   2015    Male   Non-PMETs             22.05
7   2015    Male       PMETs             18.20
8   2016  Female   Non-PMETs             22.90
9   2016  Female       PMETs             17.55
10  2016    Male   Non-PMETs             20.00
11  2016    Male       PMETs             21.25
12  2017  Female   Non-PMETs             21.40
13  2017  Female       PMETs             17.45
14  2017    Male   Non-PMETs             23.50
15  2017    Male       PMETs             20.45
16  2018  Female   Non-PMETs             19.40
17  2018  Female       PMETs             17.15
18  2018    Male   Non-PMETs             20.00
19  2018    Male       PMETs             20.85
20  2019  Female   Non-PMETs             23.50
21  2019  Female       PMETs             19.10
22  2019    Male   Non-PMETs             22.40
23  2019    Male       PMETs             20.00
24  2020  Female   Non-PMETs             32.60
25  2020  Female       PMETs             21.30
26  2020    Male   Non-PMETs             27.90
27  2020    Male       PMETs             26.90
28  2021  Female   Non-PMETs             24.35
29  2021  Female       PMETs             23.00
30  2021    Male   Non-PMETs             21.75
31  2021    Male       PMETs             27.70
32  2022  Female   Non-PMETs             21.00
33  2022  Female       PMETs             17.60
34  2022    Male   Non-PMETs             18.20
35  2022    Male       PMETs             22.00
36  2023  Female   Non-PMETs             17.30
37  2023  Female       PMETs             16.05
38  2023    Male   Non-PMETs             15.30
39  2023    Male       PMETs             20.35
40  2024  Female   Non-PMETs             15.20
41  2024  Female       PMETs             17.15
42  2024    Male   Non-PMETs             15.10
43  2024    Male       PMETs             24.05
   Gender Pmet_Status  2023
0     ALL   Non-PMETs  14.9
1  Female   Non-PMETs  17.3
2  Female       PMETs  16.0
3    Male   Non-PMETs  15.3
4    Male       PMETs  20.3

In [20]:
# Save to CSV
#occupation_split_df.to_csv('occupation_split_results.csv', index=False)

In [21]:
print(K17.head())
K17[['2014']][(K17['Age'] == '15 - 29') & (K17['Pmet_Status'] == 'PMETs')]

         Age  2014  2015  2016  2017  2018  2019  2020  2021  2022  2023  \
0    15 - 29   0.7   0.6   0.7   0.8   0.7   0.6   1.1   0.6   0.6   0.2
1    30 - 39   1.4   1.3   2.3   1.6   2.3   1.0   1.5   2.2   1.1   0.7
2    40 - 49   2.5   2.6   3.4   3.1   3.0   1.9   3.2   3.8   1.3   1.7
3  50 & Over   2.4   3.6   4.4   3.3   4.9   3.9   4.6   5.2   4.1   3.7
4    15 - 29   0.9   1.2   1.0   1.2   1.2   1.1   2.0   1.1   0.3   0.5

   2024 Pmet_Status                                              Group  \
0   0.8       PMETs  Residents Aged Fifteen Years And Over Who Have...
1   1.6       PMETs  Residents Aged Fifteen Years And Over Who Have...
2   2.6       PMETs  Residents Aged Fifteen Years And Over Who Have...
3   5.6       PMETs  Residents Aged Fifteen Years And Over Who Have...
4   0.8   Non-PMETs  Residents Aged Fifteen Years And Over Who Have...

      Status
0  Long-term
1  Long-term
2  Long-term
3  Long-term
4  Long-term

   2014
0   0.7
8   7.6

In [22]:
occupation_split_df.head()

,Occupation,Age_Group,Occupation_Count,Year,Gender,Pmet_Status
0,Managers & Administrators (Including Working P...,15 - 29,1.554971,2014,Male,PMETs
1,Professionals,15 - 29,1.246446,2014,Male,PMETs
2,Associate Professionals & Technicians,15 - 29,1.603967,2014,Male,PMETs
3,Managers & Administrators (Including Working P...,30 - 39,1.615053,2014,Male,PMETs
4,Professionals,30 - 39,1.289583,2014,Male,PMETs

In [74]:
occupation_split_df.groupby(['Pmet_Status','Age_Group','Year','Gender'], as_index=False).sum().drop(['Occupation'], axis =1).loc[lambda df: (df['Year'] == '2014') & (df['Age_Group'] == '15 - 29') & (df['Pmet_Status'] == 'PMETs')]
occupation_split_df.groupby(['Pmet_Status','Age_Group','Year','Occupation'], as_index=False).sum().drop(['Gender'], axis =1).loc[lambda df: (df['Year'] == '2014') & (df['Age_Group'] == '15 - 29') & (df['Pmet_Status'] == 'PMETs')]

,Pmet_Status,Age_Group,Year,Occupation,Occupation_Count
264,PMETs,15 - 29,2014,Associate Professionals & Technicians,3.233524
265,PMETs,15 - 29,2014,Managers & Administrators (Including Working P...,2.390801
266,PMETs,15 - 29,2014,Professionals,2.675675

In [84]:
print(3.233524 + 2.390801 +2.675675  , 0.7 + 7.6)

8.3 8.299999999999999

In [127]:
year = 2014
year_str = str(year)
age =   '15 - 29'
pmet_status = 'PMETs'

# Get K15 values and labels (Occupation totals)
k17_vals = K17[(K17['Age'] == age ) & (K17['Pmet_Status'] == pmet_status)][year_str] 
k17_labels = K17[(K17['Age'] == age ) & (K17['Pmet_Status'] == pmet_status)]['Status']
# print(k17_vals)
# print(k17_labels)

# Get K16 values and labels (Age group totals from final_result)
occupation_split_df_grouped = (occupation_split_df
                                .groupby(['Pmet_Status','Age_Group','Year','Occupation'], as_index=False)
                                .sum()
                                .drop(['Gender'], axis =1))
occupation_split_df_filtered = (occupation_split_df_grouped
                                .loc[lambda df: (df['Year'] == year_str ) & (df['Age_Group'] == age) & (df['Pmet_Status'] == pmet_status)])
occupation_split_grouped_vals = occupation_split_df_filtered['Occupation_Count']
occupation_split_grouped_labels = occupation_split_df_filtered['Occupation']
# print(occupation_split_grouped_vals)
# print(occupation_split_grouped_labels)

# Run optimization
weights_df = optimize_weights(occupation_split_grouped_vals, occupation_split_grouped_labels,k17_vals, k17_labels)
# print(weights_df)

# Melt to long format
melted = weights_df.reset_index(names='Occupation').melt(
    id_vars='Occupation',
    value_vars=k17_labels.tolist(),
    var_name='Status',
    value_name='Weight'
)

# Add columns for merging
melted['Year'] = year_str
melted['Age_Group'] = age
melted['Pmet_Status'] = pmet_status

print(melted)
# Merge with final_result to get age group marginal totals
merge_keys = ['Pmet_Status', 'Age_Group', 'Status']
table_K17 = K17[(K17['Age'] == age ) & (K17['Pmet_Status'] == pmet_status)].rename(columns={year_str: 'Occupation_Count', 'Age': 'Age_Group'}, inplace=False)
#print(table_K17)
melted = melted.merge(
    table_K17[merge_keys + ['Occupation_Count']],
    on=merge_keys,
    how='left'
)

melted['Status_Count'] = melted['Weight'] * melted['Occupation_Count']

melted

                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.409092
1  Managers & Administrators (Including Working P...   Long-term  0.261426
2                                      Professionals   Long-term  0.329482
3              Associate Professionals & Technicians  Short-term  0.387784
4  Managers & Administrators (Including Working P...  Short-term  0.290500
5                                      Professionals  Short-term  0.321715

   Year Age_Group Pmet_Status
0  2014   15 - 29       PMETs
1  2014   15 - 29       PMETs
2  2014   15 - 29       PMETs
3  2014   15 - 29       PMETs
4  2014   15 - 29       PMETs
5  2014   15 - 29       PMETs

,Occupation,Status,Weight,Year,Age_Group,Pmet_Status,Occupation_Count,Status_Count
0,Associate Professionals & Technicians,Long-term,0.409092,2014,15 - 29,PMETs,0.7,0.286364
1,Managers & Administrators (Including Working P...,Long-term,0.261426,2014,15 - 29,PMETs,0.7,0.182998
2,Professionals,Long-term,0.329482,2014,15 - 29,PMETs,0.7,0.230637
3,Associate Professionals & Technicians,Short-term,0.387784,2014,15 - 29,PMETs,7.6,2.947160
4,Managers & Administrators (Including Working P...,Short-term,0.290500,2014,15 - 29,PMETs,7.6,2.207802
5,Professionals,Short-term,0.321715,2014,15 - 29,PMETs,7.6,2.445038

In [129]:
def get_split(year, age, pmet_status):
    year_str = str(year)

    # Get K15 values and labels (Occupation totals)
    k17_vals = K17[(K17['Age'] == age ) & (K17['Pmet_Status'] == pmet_status)][year_str] 
    k17_labels = K17[(K17['Age'] == age ) & (K17['Pmet_Status'] == pmet_status)]['Status']
    # print(k17_vals)
    # print(k17_labels)
    
    # Get K16 values and labels (Age group totals from final_result)
    occupation_split_df_grouped = (occupation_split_df
                                    .groupby(['Pmet_Status','Age_Group','Year','Occupation'], as_index=False)
                                    .sum()
                                    .drop(['Gender'], axis =1))
    occupation_split_df_filtered = (occupation_split_df_grouped
                                    .loc[lambda df: (df['Year'] == year_str ) & (df['Age_Group'] == age) & (df['Pmet_Status'] == pmet_status)])
    occupation_split_grouped_vals = occupation_split_df_filtered['Occupation_Count']
    occupation_split_grouped_labels = occupation_split_df_filtered['Occupation']
    # print(occupation_split_grouped_vals)
    # print(occupation_split_grouped_labels)
    
    # Run optimization
    weights_df = optimize_weights(occupation_split_grouped_vals, occupation_split_grouped_labels,k17_vals, k17_labels)
    # print(weights_df)
    
    # Melt to long format
    melted = weights_df.reset_index(names='Occupation').melt(
        id_vars='Occupation',
        value_vars=k17_labels.tolist(),
        var_name='Status',
        value_name='Weight'
    )
    
    # Add columns for merging
    melted['Year'] = year_str
    melted['Age_Group'] = age
    melted['Pmet_Status'] = pmet_status
    
    print(melted)
    # Merge with final_result to get age group marginal totals
    merge_keys = ['Pmet_Status', 'Age_Group', 'Status']
    table_K17 = K17[(K17['Age'] == age ) & (K17['Pmet_Status'] == pmet_status)].rename(columns={year_str: 'Occupation_Count', 'Age': 'Age_Group'}, inplace=False)
    #print(table_K17)
    melted = melted.merge(
        table_K17[merge_keys + ['Occupation_Count']],
        on=merge_keys,
        how='left'
    )
    
    melted['Status_Count'] = melted['Weight'] * melted['Occupation_Count']  

    # Clean up
    melted = melted[['Occupation', 'Age_Group', 'Status_Count', 'Year', 'Pmet_Status', 'Status']]

    return melted

melted = get_split(2014, '15 - 29', 'PMETs')
melted

                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.409092
1  Managers & Administrators (Including Working P...   Long-term  0.261426
2                                      Professionals   Long-term  0.329482
3              Associate Professionals & Technicians  Short-term  0.387784
4  Managers & Administrators (Including Working P...  Short-term  0.290500
5                                      Professionals  Short-term  0.321715

   Year Age_Group Pmet_Status
0  2014   15 - 29       PMETs
1  2014   15 - 29       PMETs
2  2014   15 - 29       PMETs
3  2014   15 - 29       PMETs
4  2014   15 - 29       PMETs
5  2014   15 - 29       PMETs

,Occupation,Age_Group,Status_Count,Year,Pmet_Status,Status
0,Associate Professionals & Technicians,15 - 29,0.286364,2014,PMETs,Long-term
1,Managers & Administrators (Including Working P...,15 - 29,0.182998,2014,PMETs,Long-term
2,Professionals,15 - 29,0.230637,2014,PMETs,Long-term
3,Associate Professionals & Technicians,15 - 29,2.947160,2014,PMETs,Short-term
4,Managers & Administrators (Including Working P...,15 - 29,2.207802,2014,PMETs,Short-term
5,Professionals,15 - 29,2.445038,2014,PMETs,Short-term

In [137]:
# Define the ranges for the loop
years = range(2014, 2025)  # From 2014 to 2024
pmet_statuses = ['PMETs', 'Non-PMETs']
ages = ['15 - 29', '30 - 39', '40 - 49', '50 & Over']

# Initialize an empty list to store the results
all_melted = []

# Loop over all combinations of year, pmet_status, and age
for year in years:
    for pmet_status in pmet_statuses:
        for age in ages:
            print(f"Processing: Year={year}, Age={age}, PMET Status={pmet_status}")
            melted = get_split(year, age, pmet_status)
            all_melted.append(melted)

# Concatenate all results into one DataFrame
status_split_result = pd.concat(all_melted, ignore_index=True)

# Optionally, you can inspect the final result or save it to a file
status_split_result

Processing: Year=2014, Age=15 - 29, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.409092
1  Managers & Administrators (Including Working P...   Long-term  0.261426
2                                      Professionals   Long-term  0.329482
3              Associate Professionals & Technicians  Short-term  0.387784
4  Managers & Administrators (Including Working P...  Short-term  0.290500
5                                      Professionals  Short-term  0.321715

   Year Age_Group Pmet_Status
0  2014   15 - 29       PMETs
1  2014   15 - 29       PMETs
2  2014   15 - 29       PMETs
3  2014   15 - 29       PMETs
4  2014   15 - 29       PMETs
5  2014   15 - 29       PMETs
Processing: Year=2014, Age=30 - 39, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.417435
1  Managers & Administrators (Including Working P...   Long-term  0.258122
2                                      Professionals   Long-term  0.324442
3              Associate Professionals & Technicians  Short-term  0.383641
4  Managers & Administrators (Including Working P...  Short-term  0.293340
5                                      Professionals  Short-term  0.323019

   Year Age_Group Pmet_Status
0  2014   30 - 39       PMETs
1  2014   30 - 39       PMETs
2  2014   30 - 39       PMETs
3  2014   30 - 39       PMETs
4  2014   30 - 39       PMETs
5  2014   30 - 39       PMETs
Processing: Year=2014, Age=40 - 49, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.403955
1  Managers & Administrators (Including Working P...   Long-term  0.270244
2                                      Professionals   Long-term  0.325801
3              Associate Professionals & Technicians  Short-term  0.382963
4  Managers & Administrators (Including Working P...  Short-term  0.294418
5                                      Professionals  Short-term  0.322619

   Year Age_Group Pmet_Status
0  2014   40 - 49       PMETs
1  2014   40 - 49       PMETs
2  2014   40 - 49       PMETs
3  2014   40 - 49       PMETs
4  2014   40 - 49       PMETs
5  2014   40 - 49       PMETs
Processing: Year=2014, Age=50 & Over, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.396791
1  Managers & Administrators (Including Working P...   Long-term  0.285513
2                                      Professionals   Long-term  0.317696
3              Associate Professionals & Technicians  Short-term  0.388882
4  Managers & Administrators (Including Working P...  Short-term  0.292440
5                                      Professionals  Short-term  0.318677

   Year  Age_Group Pmet_Status
0  2014  50 & Over       PMETs
1  2014  50 & Over       PMETs
2  2014  50 & Over       PMETs
3  2014  50 & Over       PMETs
4  2014  50 & Over       PMETs
5  2014  50 & Over       PMETs
Processing: Year=2014, Age=15 - 29, PMET Status=Non-PMETs
                                Occupation      Status    Weight  Year  \
0    Cleaners, Labourers & Related Workers   Long-term  0.189919  2014
1                 Clerical Support Workers   Long-term  0.142853  2014
2       Craftsmen & Related Trades Workers   Long-term  0.151372  2014
3                                   Others   Long-term  0.089031  2014
4   Plant & Machine Operators & Assemblers   Long-term  0.199353  2014
5                  Service & Sales Workers   Long-term  0.227472  2014
6    Cleaners, Labourers & Related Workers  Short-term  0.184369  2014
7                 Clerical Support Workers  Short-term  0.188491  2014
8       Craftsmen & Related Trades Workers  Short-term  0.125374  2014
9                                   Others  Short-term  0.086660  2014
10  Plant & Machine Operators & Assemblers  Short-term  0.186761  2014
11                 Service & Sales Workers  Short-term  0.228344  2014

   Age_Group Pmet_Status
0    15 - 29   Non-PMETs
1    15 - 29   Non-PMETs
2    15 - 29   Non-PMETs
3    15 - 29   Non-PMETs
4    15 - 29   Non-PMETs
5    15 - 29   Non-PMETs
6    15 - 29   Non-PMETs
7    15 - 29   Non-PMETs
8    15 - 29   Non-PMETs
9    15 - 29   Non-PMETs
10   15 - 29   Non-PMETs
11   15 - 29   Non-PMETs
Processing: Year=2014, Age=30 - 39, PMET Status=Non-PMETs
                                Occupation      Status    Weight  Year  \
0    Cleaners, Labourers & Related Workers   Long-term  0.165035  2014
1                 Clerical Support Workers   Long-term  0.188140  2014
2       Craftsmen & Related Trades Workers   Long-term  0.111983  2014
3                                   Others   Long-term  0.099177  2014
4   Plant & Machine Operators & Assemblers   Long-term  0.176838  2014
5                  Service & Sales Workers   Long-term  0.258826  2014
6    Cleaners, Labourers & Related Workers  Short-term  0.171405  2014
7                 Clerical Support Workers  Short-term  0.180665  2014
8       Craftsmen & Related Trades Workers  Short-term  0.138052  2014
9                                   Others  Short-term  0.087813  2014
10  Plant & Machine Operators & Assemblers  Short-term  0.171721  2014
11                 Service & Sales Workers  Short-term  0.250344  2014

   Age_Group Pmet_Status
0    30 - 39   Non-PMETs
1    30 - 39   Non-PMETs
2    30 - 39   Non-PMETs
3    30 - 39   Non-PMETs
4    30 - 39   Non-PMETs
5    30 - 39   Non-PMETs
6    30 - 39   Non-PMETs
7    30 - 39   Non-PMETs
8    30 - 39   Non-PMETs
9    30 - 39   Non-PMETs
10   30 - 39   Non-PMETs
11   30 - 39   Non-PMETs
Processing: Year=2014, Age=40 - 49, PMET Status=Non-PMETs
                                Occupation      Status    Weight  Year  \
0    Cleaners, Labourers & Related Workers   Long-term  0.169003  2014
1                 Clerical Support Workers   Long-term  0.173976  2014
2       Craftsmen & Related Trades Workers   Long-term  0.113302  2014
3                                   Others   Long-term  0.100144  2014
4   Plant & Machine Operators & Assemblers   Long-term  0.168354  2014
5                  Service & Sales Workers   Long-term  0.275221  2014
6    Cleaners, Labourers & Related Workers  Short-term  0.171959  2014
7                 Clerical Support Workers  Short-term  0.184028  2014
8       Craftsmen & Related Trades Workers  Short-term  0.139640  2014
9                                   Others  Short-term  0.085188  2014
10  Plant & Machine Operators & Assemblers  Short-term  0.174074  2014
11                 Service & Sales Workers  Short-term  0.245111  2014

   Age_Group Pmet_Status
0    40 - 49   Non-PMETs
1    40 - 49   Non-PMETs
2    40 - 49   Non-PMETs
3    40 - 49   Non-PMETs
4    40 - 49   Non-PMETs
5    40 - 49   Non-PMETs
6    40 - 49   Non-PMETs
7    40 - 49   Non-PMETs
8    40 - 49   Non-PMETs
9    40 - 49   Non-PMETs
10   40 - 49   Non-PMETs
11   40 - 49   Non-PMETs
Processing: Year=2014, Age=50 & Over, PMET Status=Non-PMETs
                                Occupation      Status    Weight  Year  \
0    Cleaners, Labourers & Related Workers   Long-term  0.146644  2014
1                 Clerical Support Workers   Long-term  0.186187  2014
2       Craftsmen & Related Trades Workers   Long-term  0.119601  2014
3                                   Others   Long-term  0.092103  2014
4   Plant & Machine Operators & Assemblers   Long-term  0.193887  2014
5                  Service & Sales Workers   Long-term  0.261578  2014
6    Cleaners, Labourers & Related Workers  Short-term  0.193716  2014
7                 Clerical Support Workers  Short-term  0.185156  2014
8       Craftsmen & Related Trades Workers  Short-term  0.131075  2014
9                                   Others  Short-term  0.085001  2014
10  Plant & Machine Operators & Assemblers  Short-term  0.182303  2014
11                 Service & Sales Workers  Short-term  0.222748  2014

    Age_Group Pmet_Status
0   50 & Over   Non-PMETs
1   50 & Over   Non-PMETs
2   50 & Over   Non-PMETs
3   50 & Over   Non-PMETs
4   50 & Over   Non-PMETs
5   50 & Over   Non-PMETs
6   50 & Over   Non-PMETs
7   50 & Over   Non-PMETs
8   50 & Over   Non-PMETs
9   50 & Over   Non-PMETs
10  50 & Over   Non-PMETs
11  50 & Over   Non-PMETs
Processing: Year=2015, Age=15 - 29, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.427836
1  Managers & Administrators (Including Working P...   Long-term  0.261060
2                                      Professionals   Long-term  0.311104
3              Associate Professionals & Technicians  Short-term  0.420539
4  Managers & Administrators (Including Working P...  Short-term  0.252154
5                                      Professionals  Short-term  0.327308

   Year Age_Group Pmet_Status
0  2015   15 - 29       PMETs
1  2015   15 - 29       PMETs
2  2015   15 - 29       PMETs
3  2015   15 - 29       PMETs
4  2015   15 - 29       PMETs
5  2015   15 - 29       PMETs
Processing: Year=2015, Age=30 - 39, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.434857
1  Managers & Administrators (Including Working P...   Long-term  0.258795
2                                      Professionals   Long-term  0.306347
3              Associate Professionals & Technicians  Short-term  0.418309
4  Managers & Administrators (Including Working P...  Short-term  0.252554
5                                      Professionals  Short-term  0.329138

   Year Age_Group Pmet_Status
0  2015   30 - 39       PMETs
1  2015   30 - 39       PMETs
2  2015   30 - 39       PMETs
3  2015   30 - 39       PMETs
4  2015   30 - 39       PMETs
5  2015   30 - 39       PMETs
Processing: Year=2015, Age=40 - 49, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.427556
1  Managers & Administrators (Including Working P...   Long-term  0.254129
2                                      Professionals   Long-term  0.318315
3              Associate Professionals & Technicians  Short-term  0.416226
4  Managers & Administrators (Including Working P...  Short-term  0.243210
5                                      Professionals  Short-term  0.340564

   Year Age_Group Pmet_Status
0  2015   40 - 49       PMETs
1  2015   40 - 49       PMETs
2  2015   40 - 49       PMETs
3  2015   40 - 49       PMETs
4  2015   40 - 49       PMETs
5  2015   40 - 49       PMETs
Processing: Year=2015, Age=50 & Over, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.422883
1  Managers & Administrators (Including Working P...   Long-term  0.249502
2                                      Professionals   Long-term  0.327615
3              Associate Professionals & Technicians  Short-term  0.417262
4  Managers & Administrators (Including Working P...  Short-term  0.244292
5                                      Professionals  Short-term  0.338446

   Year  Age_Group Pmet_Status
0  2015  50 & Over       PMETs
1  2015  50 & Over       PMETs
2  2015  50 & Over       PMETs
3  2015  50 & Over       PMETs
4  2015  50 & Over       PMETs
5  2015  50 & Over       PMETs
Processing: Year=2015, Age=15 - 29, PMET Status=Non-PMETs
                                Occupation      Status    Weight  Year  \
0    Cleaners, Labourers & Related Workers   Long-term  0.167368  2015
1                 Clerical Support Workers   Long-term  0.156862  2015
2       Craftsmen & Related Trades Workers   Long-term  0.160726  2015
3                                   Others   Long-term  0.084590  2015
4   Plant & Machine Operators & Assemblers   Long-term  0.174136  2015
5                  Service & Sales Workers   Long-term  0.256317  2015
6    Cleaners, Labourers & Related Workers  Short-term  0.173100  2015
7                 Clerical Support Workers  Short-term  0.189385  2015
8       Craftsmen & Related Trades Workers  Short-term  0.128397  2015
9                                   Others  Short-term  0.085709  2015
10  Plant & Machine Operators & Assemblers  Short-term  0.179473  2015
11                 Service & Sales Workers  Short-term  0.243936  2015

   Age_Group Pmet_Status
0    15 - 29   Non-PMETs
1    15 - 29   Non-PMETs
2    15 - 29   Non-PMETs
3    15 - 29   Non-PMETs
4    15 - 29   Non-PMETs
5    15 - 29   Non-PMETs
6    15 - 29   Non-PMETs
7    15 - 29   Non-PMETs
8    15 - 29   Non-PMETs
9    15 - 29   Non-PMETs
10   15 - 29   Non-PMETs
11   15 - 29   Non-PMETs
Processing: Year=2015, Age=30 - 39, PMET Status=Non-PMETs
                                Occupation      Status    Weight  Year  \
0    Cleaners, Labourers & Related Workers   Long-term  0.162264  2015
1                 Clerical Support Workers   Long-term  0.176787  2015
2       Craftsmen & Related Trades Workers   Long-term  0.155699  2015
3                                   Others   Long-term  0.087847  2015
4   Plant & Machine Operators & Assemblers   Long-term  0.127317  2015
5                  Service & Sales Workers   Long-term  0.290085  2015
6    Cleaners, Labourers & Related Workers  Short-term  0.160557  2015
7                 Clerical Support Workers  Short-term  0.181622  2015
8       Craftsmen & Related Trades Workers  Short-term  0.153789  2015
9                                   Others  Short-term  0.089766  2015
10  Plant & Machine Operators & Assemblers  Short-term  0.146078  2015
11                 Service & Sales Workers  Short-term  0.268187  2015

   Age_Group Pmet_Status
0    30 - 39   Non-PMETs
1    30 - 39   Non-PMETs
2    30 - 39   Non-PMETs
3    30 - 39   Non-PMETs
4    30 - 39   Non-PMETs
5    30 - 39   Non-PMETs
6    30 - 39   Non-PMETs
7    30 - 39   Non-PMETs
8    30 - 39   Non-PMETs
9    30 - 39   Non-PMETs
10   30 - 39   Non-PMETs
11   30 - 39   Non-PMETs
Processing: Year=2015, Age=40 - 49, PMET Status=Non-PMETs
                                Occupation      Status    Weight  Year  \
0    Cleaners, Labourers & Related Workers   Long-term  0.159276  2015
1                 Clerical Support Workers   Long-term  0.169663  2015
2       Craftsmen & Related Trades Workers   Long-term  0.151031  2015
3                                   Others   Long-term  0.094090  2015
4   Plant & Machine Operators & Assemblers   Long-term  0.126036  2015
5                  Service & Sales Workers   Long-term  0.299905  2015
6    Cleaners, Labourers & Related Workers  Short-term  0.161818  2015
7                 Clerical Support Workers  Short-term  0.183526  2015
8       Craftsmen & Related Trades Workers  Short-term  0.153420  2015
9                                   Others  Short-term  0.087343  2015
10  Plant & Machine Operators & Assemblers  Short-term  0.147307  2015
11                 Service & Sales Workers  Short-term  0.266585  2015

   Age_Group Pmet_Status
0    40 - 49   Non-PMETs
1    40 - 49   Non-PMETs
2    40 - 49   Non-PMETs
3    40 - 49   Non-PMETs
4    40 - 49   Non-PMETs
5    40 - 49   Non-PMETs
6    40 - 49   Non-PMETs
7    40 - 49   Non-PMETs
8    40 - 49   Non-PMETs
9    40 - 49   Non-PMETs
10   40 - 49   Non-PMETs
11   40 - 49   Non-PMETs
Processing: Year=2015, Age=50 & Over, PMET Status=Non-PMETs
                                Occupation      Status    Weight  Year  \
0    Cleaners, Labourers & Related Workers   Long-term  0.172756  2015
1                 Clerical Support Workers   Long-term  0.156399  2015
2       Craftsmen & Related Trades Workers   Long-term  0.149828  2015
3                                   Others   Long-term  0.080346  2015
4   Plant & Machine Operators & Assemblers   Long-term  0.192047  2015
5                  Service & Sales Workers   Long-term  0.248624  2015
6    Cleaners, Labourers & Related Workers  Short-term  0.171858  2015
7                 Clerical Support Workers  Short-term  0.195871  2015
8       Craftsmen & Related Trades Workers  Short-term  0.126080  2015
9                                   Others  Short-term  0.086840  2015
10  Plant & Machine Operators & Assemblers  Short-term  0.174507  2015
11                 Service & Sales Workers  Short-term  0.244844  2015

    Age_Group Pmet_Status
0   50 & Over   Non-PMETs
1   50 & Over   Non-PMETs
2   50 & Over   Non-PMETs
3   50 & Over   Non-PMETs
4   50 & Over   Non-PMETs
5   50 & Over   Non-PMETs
6   50 & Over   Non-PMETs
7   50 & Over   Non-PMETs
8   50 & Over   Non-PMETs
9   50 & Over   Non-PMETs
10  50 & Over   Non-PMETs
11  50 & Over   Non-PMETs
Processing: Year=2016, Age=15 - 29, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.405567
1  Managers & Administrators (Including Working P...   Long-term  0.264108
2                                      Professionals   Long-term  0.330326
3              Associate Professionals & Technicians  Short-term  0.392367
4  Managers & Administrators (Including Working P...  Short-term  0.277054
5                                      Professionals  Short-term  0.330579

   Year Age_Group Pmet_Status
0  2016   15 - 29       PMETs
1  2016   15 - 29       PMETs
2  2016   15 - 29       PMETs
3  2016   15 - 29       PMETs
4  2016   15 - 29       PMETs
5  2016   15 - 29       PMETs
Processing: Year=2016, Age=30 - 39, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.414401
1  Managers & Administrators (Including Working P...   Long-term  0.256600
2                                      Professionals   Long-term  0.328999
3              Associate Professionals & Technicians  Short-term  0.387435
4  Managers & Administrators (Including Working P...  Short-term  0.270941
5                                      Professionals  Short-term  0.341624

   Year Age_Group Pmet_Status
0  2016   30 - 39       PMETs
1  2016   30 - 39       PMETs
2  2016   30 - 39       PMETs
3  2016   30 - 39       PMETs
4  2016   30 - 39       PMETs
5  2016   30 - 39       PMETs
Processing: Year=2016, Age=40 - 49, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.403424
1  Managers & Administrators (Including Working P...   Long-term  0.263435
2                                      Professionals   Long-term  0.333140
3              Associate Professionals & Technicians  Short-term  0.388254
4  Managers & Administrators (Including Working P...  Short-term  0.272373
5                                      Professionals  Short-term  0.339373

   Year Age_Group Pmet_Status
0  2016   40 - 49       PMETs
1  2016   40 - 49       PMETs
2  2016   40 - 49       PMETs
3  2016   40 - 49       PMETs
4  2016   40 - 49       PMETs
5  2016   40 - 49       PMETs
Processing: Year=2016, Age=50 & Over, PMET Status=PMETs
                                          Occupation      Status    Weight  \
0              Associate Professionals & Technicians   Long-term  0.397920
1  Managers & Administrators (Including Working P...   Long-term  0.264801
2                                      Professionals   Long-term  0.337278
3              Associate Professionals & Technicians  Short-term  0.390181
4  Managers & Administrators (Including Working P...  Short-term  0.269214
5                                      Professionals  Short-term  0.340606

   Year  Age_Group Pmet_Status
0  2016  50 & Over       PMETs
1  2016  50 & Over       PMETs
2  2016  50 & Over       PMETs
3  2016  50 & Over       PMETs

,Occupation,Age_Group,Status_Count,Year,Pmet_Status,Status
0,Associate Professionals & Technicians,15 - 29,0.286364,2014,PMETs,Long-term
1,Managers & Administrators (Including Working P...,15 - 29,0.182998,2014,PMETs,Long-term
2,Professionals,15 - 29,0.230637,2014,PMETs,Long-term
3,Associate Professionals & Technicians,15 - 29,2.947160,2014,PMETs,Short-term
4,Managers & Administrators (Including Working P...,15 - 29,2.207802,2014,PMETs,Short-term
...,...,...,...,...,...,...
787,Clerical Support Workers,50 & Over,3.695635,2024,Non-PMETs,Short-term
788,Craftsmen & Related Trades Workers,50 & Over,0.453996,2024,Non-PMETs,Short-term
789,Others,50 & Over,0.154176,2024,Non-PMETs,Short-term
790,Plant & Machine Operators & Assemblers,50 & Over,1.252844,2024,Non-PMETs,Short-term
791,Service & Sales Workers,50 & Over,3.570119,2024,Non-PMETs,Short-term

In [177]:
print(status_split_result.columns)
print(status_split_result[['Status_Count','Status']][ (status_split_result['Year'] == '2014' ) & (status_split_result['Age_Group'] == '15 - 29') & (status_split_result['Occupation'] == 'Associate Professionals & Technicians')])
status_split_result[['Status_Count']][ (status_split_result['Year'] == '2014' ) & (status_split_result['Age_Group'] == '15 - 29') & (status_split_result['Occupation'] == 'Associate Professionals & Technicians')].sum()

Index(['Occupation', 'Age_Group', 'Status_Count', 'Year', 'Pmet_Status',
       'Status'],
      dtype='object')
   Status_Count      Status
0      0.286364   Long-term
3      2.947160  Short-term

Status_Count    3.233524
dtype: float64

In [178]:
print(occupation_split_df.columns)
print(occupation_split_df [['Occupation_Count', 'Gender']][ (occupation_split_df['Year'] == '2014') &  (occupation_split_df['Age_Group'] == '15 - 29') & (occupation_split_df['Occupation'] == 'Associate Professionals & Technicians')])
print(occupation_split_df ['Occupation_Count'][ (occupation_split_df['Year'] == '2014') &  (occupation_split_df['Age_Group'] == '15 - 29') & (occupation_split_df['Occupation'] == 'Associate Professionals & Technicians')].sum())

Index(['Occupation', 'Age_Group', 'Occupation_Count', 'Year', 'Gender',
       'Pmet_Status'],
      dtype='object')
    Occupation_Count  Gender
2           1.603967    Male
14          1.629557  Female
3.233524327446845

In [192]:
import numpy as np

Year = '2014'
age = '15 - 29' 
occupation = 'Associate Professionals & Technicians'

# Coefficients for Long-term and Short-term
long_term = status_split_result['Status_Count'][ (status_split_result['Status'] == 'Long-term' ) & (status_split_result['Year'] == Year ) & (status_split_result['Age_Group'] == age ) & (status_split_result['Occupation'] == occupation)].values[0]
short_term = status_split_result['Status_Count'][ (status_split_result['Status'] == 'Short-term' ) & (status_split_result['Year'] == Year ) & (status_split_result['Age_Group'] == age ) & (status_split_result['Occupation'] == occupation)].values[0]
total_male = occupation_split_df ['Occupation_Count'][ (occupation_split_df['Gender'] == 'Male') & (occupation_split_df['Year'] == Year ) &  (occupation_split_df['Age_Group'] == age ) & (occupation_split_df['Occupation'] == occupation)].values[0]
total_female = occupation_split_df ['Occupation_Count'][ (occupation_split_df['Gender'] == 'Female') & (occupation_split_df['Year'] == Year ) &  (occupation_split_df['Age_Group'] == age ) & (occupation_split_df['Occupation'] == occupation)].values[0]

# Build the system: 4 equations in 4 unknowns
# total_male = w1 * long_term + w2 * short_term
# total_female = w3 * long_term + w4 * short_term
# w1 + w3 = 1
# w2 + w4 = 1

A = np.array([
    [long_term, short_term,        0,        0],     # w1, w2
    [0,         0,         long_term, short_term],   # w3, w4
    [1,         0,         1,        0],            # w1 + w3
    [0,         1,         0,        1]             # w2 + w4
])
b = np.array([total_male, total_female, 1, 1])

# Solve using least-squares
weights, _, _, _ = np.linalg.lstsq(A, b, rcond=None)

print("Weights: ", weights) # w1, w2, w3 ,w4

Weights:  [0.49958211 0.4956992  0.50041789 0.5043008 ]

In [ ]:
# build for loop for (['Occupation', 'Age_Group', 'Year', 'Pmet_Status'],